blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='allblogs'),
    path('<int:blog_id>', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.portfolio, name='portfolio'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=64)
    date = models.DateField()
    description = models.CharField(max_length=248)
    textar = models.TextField(default='')

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def all_blogs(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html', {'blogs':blogs})
def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog} )

portfolio/views.py
from django.shortcuts import render
from .models import Project

def portfolio(request):
    projects = Project.objects.all()
    return render(request, 'portfolio.html', {'projects': projects})

blog/templates/blog/all_blogs.html
{% extends 'base.html'%}
{% block body %}


<h1>Eugene has {{ blogs.count }} blog{{ blogs.count|pluralize }}</<h4></h4>
<br>
<div class="container text-start">
{% for blog in blogs %}
<a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
<p class="fst-italic">{{ blog.date|date:'d F y'|upper }}</p>
<p class="fst-normal">{{ blog.description|safe|truncatechars:100 }}</p>
<br>
{% endfor %}
</div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'base.html'%}
{% block body %}
<h1>{{ blog.title }}</h1>
<br>
<div class="container text-start">
{{ blog.textar|safe }}
</div>
{% endblock%}

portfolio/templates/base.html
  <!doctype html>
  {% load static %}
  <html lang="en">
    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <!-- Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
      <link rel="icon" href="{% static 'portfolio/robot.png' %}">
      <link rel="shortcut icon" href="{% static 'portfolio/robot.png' %}">
      <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300&display=swap" rel="stylesheet">
      <link href="{% static 'portfolio/style.css' %}" rel="stylesheet">

      <title>Eugene BIZUNOK</title>
    </head>
    <body>
      <div class="container">
        <header class="d-flex justify-content-between py-3 mb-4 border-bottom">
            <a class="navbar-brand link-dark" href="{% url 'portfolio' %}">
            <div class="bd-highlight pe-5">
              <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-robot mb-2" viewBox="0 0 16 16">
                <path d="M6 12.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5ZM3 8.062C3 6.76 4.235 5.765 5.53 5.886a26.58 26.58 0 0 0 4.94 0C11.765 5.765 13 6.76 13 8.062v1.157a.933.933 0 0 1-.765.935c-.845.147-2.34.346-4.235.346-1.895 0-3.39-.2-4.235-.346A.933.933 0 0 1 3 9.219V8.062Zm4.542-.827a.25.25 0 0 0-.217.068l-.92.9a24.767 24.767 0 0 1-1.871-.183.25.25 0 0 0-.068.495c.55.076 1.232.149 2.02.193a.25.25 0 0 0 .189-.071l.754-.736.847 1.71a.25.25 0 0 0 .404.062l.932-.97a25.286 25.286 0 0 0 1.922-.188.25.25 0 0 0-.068-.495c-.538.074-1.207.145-1.98.189a.25.25 0 0 0-.166.076l-.754.785-.842-1.7a.25.25 0 0 0-.182-.135Z"/>
                <path d="M8.5 1.866a1 1 0 1 0-1 0V3h-2A4.5 4.5 0 0 0 1 7.5V8a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1v1a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-1a1 1 0 0 0 1-1V9a1 1 0 0 0-1-1v-.5A4.5 4.5 0 0 0 10.5 3h-2V1.866ZM14 7.5V13a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V7.5A3.5 3.5 0 0 1 5.5 4h5A3.5 3.5 0 0 1 14 7.5Z"/>
              </svg>
              <span class="fs-4 p-3 fw-bold">Eugene BIZUNOK</span>
            </div>
            </a>
            <ul class="fs-5 nav justify-content-end">
              <li class="nav-item">
                <a class="nav-link fw-bold" href="{% url 'blog:allblogs' %}">Blogs</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'portfolio' %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
  <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
</svg></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://t.me/eugenebizunok"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telegram" viewBox="0 0 16 16">
  <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.287 5.906c-.778.324-2.334.994-4.666 2.01-.378.15-.577.298-.595.442-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294.26.006.549-.1.868-.32 2.179-1.471 3.304-2.214 3.374-2.23.05-.012.12-.026.166.016.047.041.042.12.037.141-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8.154 8.154 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629.093.06.183.125.27.187.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.426 1.426 0 0 0-.013-.315.337.337 0 0 0-.114-.217.526.526 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09z"/>
</svg></a>
              <li>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
              </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% static 'portfolio/Евгений Бизунок.docx' %}">Resume.docx <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
              <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
              <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
              </svg></a>
              </li>
            </ul>
          </header>
          <div class="container text-center">
          {% block body %} {% endblock %}
          </div>
        </div>
      <!-- Optional JavaScript; choose one of the two! -->

      <!-- Option 1: Bootstrap Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

      <!-- Option 2: Separate Popper and Bootstrap JS -->
      <!--
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
      -->
    </body>
  </html>

portfolio/templates/portfolio.html
{% extends 'base.html'%}
{% block body %}

{% load static %}
<div class="d-flex justify-content-evenly py-3 mb-4 border-bottom">
  <img src="{% static 'portfolio/photo.jpg' %}" width="400" class='ps-5 ms-5'>
  <h1 class="text-start py-5 mt-5 me-5">Hello!<br> My name is Eugene and...<br>Welcome to my site-portfolio!!</h1>
</div>
<h1 class="fw-bold">My projects on GitHub</h1>
<br>
<br>
{% if not projects %}
<h3 class="fst-italic fw-lighter">There are no projects, yet</h3>
{% endif %}
<div class="row">
  {% for project in projects %}
    <div class="col-lg-4 col-md-6">
      <div class="container text-center">

        {% if project.url %}
        <a class="mb-4 btn btn-outline-dark" href="{{ project.url }}">
          <img src="{{ project.image.url }}" class="card-img-top img-fluid" width="100%" height="300">
          <h3>{{ project.title }}</h3>
          <p>{{ project.description }}</p>
        </a>

        {% else %}
        <a class="mb-4 btn btn-outline-dark" href="{{ project.url }}">
          <img src="{{ project.image.url }}" class="card-img-top img-fluid" width="100%" height="300">
          <h3>{{ project.title }}</h3>
          <p>{{ project.description }}</p>
        </a>
        {% endif %}
      </div>
    </div>
  {% endfor %}
</div>

{% endblock %}